# Generated by Django 3.0.8 on 2020-07-27 01:56

import construction.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=255, null=True, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=255, null=True, verbose_name='Last Name')),
                ('suffix', models.CharField(blank=True, max_length=255, null=True, verbose_name='Suffix')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Admin - User',
                'verbose_name_plural': 'Admin - User',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Admin - City',
            },
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('call_time', models.CharField(max_length=255, verbose_name='Best time to call')),
                ('address', models.CharField(max_length=255, null=True)),
                ('lotarea', models.CharField(blank=True, help_text='Please indicate if square meter, hectare, acre', max_length=255, verbose_name='Lot Area')),
                ('budget', models.FloatField(max_length=255, verbose_name='Estimated Budget')),
                ('date_start', models.DateField(null=True, verbose_name='Estimated Date Start')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('status', models.BooleanField(default=False)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.City', verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalMaterialReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.today)),
            ],
            options={
                'verbose_name': 'Project - Material Report(External Inventory - onsite)',
                'verbose_name_plural': 'Project - Material Report(External Inventory - onsite)',
            },
        ),
        migrations.CreateModel(
            name='ExternalOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Date')),
                ('amount', models.FloatField(default=0, verbose_name='Amount')),
            ],
            options={
                'verbose_name': 'Project - External Order',
                'verbose_name_plural': 'Project - External Order',
            },
        ),
        migrations.CreateModel(
            name='ExternalProjectInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project - External Inventory(onsite)',
                'verbose_name_plural': 'Project - External Inventory(onsite)',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Admin - Gender',
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('message', models.TextField(null=True, verbose_name='Message')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternate_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alternate Code')),
                ('item_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Item Code')),
                ('unit', models.CharField(blank=True, max_length=255, null=True, verbose_name='Unit')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('unit_price', models.FloatField(default=0, verbose_name='Unit Price')),
            ],
            options={
                'verbose_name_plural': 'Admin - Material Inventory Office',
            },
        ),
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Format: yyyy-mm-dd', verbose_name='Date Given')),
                ('duration', models.DateField(help_text='Format: yyyy-mm-dd', verbose_name='Duration')),
                ('pic', models.ForeignKey(limit_choices_to={'groups__name': 'Person In-Charge'}, on_delete=django.db.models.deletion.CASCADE, related_name='joborder_pic', to=settings.AUTH_USER_MODEL, verbose_name='Prepared by')),
            ],
            options={
                'verbose_name': 'Project - Job Order',
                'verbose_name_plural': 'Project - Job Order',
            },
        ),
        migrations.CreateModel(
            name='JobOrderTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255, verbose_name='Activity of the Week')),
                ('date', models.DateField(blank=True, null=True, verbose_name='From')),
                ('date2', models.DateField(blank=True, null=True, verbose_name='To')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='Remarks')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('On-going', 'On-going')], default='Pending', max_length=255, verbose_name='Status')),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('joborder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobordertask', to='construction.JobOrder', verbose_name='Joborder')),
            ],
            options={
                'verbose_name': 'Job Order Task',
                'verbose_name_plural': 'Job Order Tasks',
            },
        ),
        migrations.CreateModel(
            name='LandingPageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Landing Page Image Category')),
            ],
            options={
                'verbose_name': 'Admin - Landing Page Image Categories',
                'verbose_name_plural': 'Admin - Landing Page Image Categories',
            },
        ),
        migrations.CreateModel(
            name='MaterialReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.today)),
            ],
            options={
                'verbose_name': 'Project - Material Report(Inventory - onsite)',
                'verbose_name_plural': 'Project - Material Report(Inventory - onsite)',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('suffix', models.CharField(blank=True, max_length=50, null=True, verbose_name='Suffix')),
                ('contact', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('address', models.CharField(help_text='Apartment, suite, unit, building, floor, street, barangay', max_length=255, null=True)),
                ('joborder_count', models.IntegerField(default=0, verbose_name='Job Order')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.City', verbose_name='City')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.Gender')),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnel',
            },
        ),
        migrations.CreateModel(
            name='PersonnelSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255, verbose_name='Skill')),
            ],
            options={
                'verbose_name': 'Admin - Personnel Skills',
                'verbose_name_plural': 'Admin - Personnel Skills',
            },
        ),
        migrations.CreateModel(
            name='PersonnelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personneltype', models.CharField(max_length=255, null=True, verbose_name='Type of Personnel')),
            ],
            options={
                'verbose_name': 'Admin - Personnel Type',
                'verbose_name_plural': 'Admin - Personnel Type',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255, null=True, verbose_name='Project Name')),
                ('address', models.CharField(help_text='Apartment, suite, unit, building, floor, street, barangay', max_length=255, null=True, verbose_name='Address')),
                ('status', models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Completed (Overdue)', 'Completed (Overdue)'), ('On-going', 'On-going')], default='Pending', max_length=255)),
                ('lotarea', models.CharField(blank=True, help_text='Please indicate if square meter, hectare, acre', max_length=255, verbose_name='Lot Area')),
                ('startdate', models.DateField(blank=True, help_text='Format: YYYY-MM-DD', null=True, verbose_name='Start Project Date')),
                ('comdate', models.DateField(blank=True, help_text='Format: YYYY-MM-DD', null=True, verbose_name='Project Completion Date')),
                ('mpd', models.DateField(blank=True, help_text='Format: YYYY-MM-DD', null=True, verbose_name='Maintenance Period End Date')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.City', verbose_name='City')),
                ('client', models.ForeignKey(limit_choices_to={'groups__name': 'Client'}, on_delete=django.db.models.deletion.CASCADE, related_name='project_client', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('pic', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Person In-Charge'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_pic', to=settings.AUTH_USER_MODEL, verbose_name='Person In Charge')),
                ('pm', models.ForeignKey(limit_choices_to={'groups__name': 'Project Manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='project_pm', to=settings.AUTH_USER_MODEL, verbose_name='Project Manager')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Project',
            },
        ),
        migrations.CreateModel(
            name='ProjectInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='construction.Project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project - Material Inventory(onsite)',
                'verbose_name_plural': 'Project - Material Inventory(onsite)',
            },
        ),
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_progress', models.FloatField(default=0)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='construction.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projecttype', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Admin - Project Type',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Admin - Province',
                'verbose_name_plural': 'Admin - Province',
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, null=True, verbose_name='Subject')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('total', models.FloatField(blank=True, default=0, verbose_name='Total Amount')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], default='Pending', max_length=255, verbose_name='Status')),
                ('is_vat', models.BooleanField(default=False, verbose_name='is VAT included?')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='construction.Project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project - Quotation',
                'verbose_name_plural': 'Project - Quotation',
            },
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='requisition number')),
                ('date', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Date')),
                ('status', models.CharField(choices=[('Closed', 'Closed'), ('Pending', 'Pending'), ('To be Delivered', 'To be Delivered')], default='Pending', max_length=255)),
                ('amount', models.FloatField(default=0, verbose_name='Total Amount')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_project', to='construction.Project', verbose_name='Project')),
                ('whm', models.ForeignKey(help_text='Warehouseman', limit_choices_to={'groups__name': 'Warehouseman'}, on_delete=django.db.models.deletion.CASCADE, related_name='requisition_whm', to=settings.AUTH_USER_MODEL, verbose_name='Prepared by')),
            ],
            options={
                'verbose_name': 'Project - Requisition',
                'verbose_name_plural': 'Project - Requisition',
            },
        ),
        migrations.CreateModel(
            name='Rework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('instruction', models.TextField()),
                ('pm', models.ForeignKey(limit_choices_to={'groups__name': 'Project Manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='rework_pm', to=settings.AUTH_USER_MODEL, verbose_name='Prepared by')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reworkform', to='construction.Project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project - Rework',
                'verbose_name_plural': 'Project - Rework',
            },
        ),
        migrations.CreateModel(
            name='ScopeOfWorkCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Admin - Category(Scope of Work)',
                'verbose_name_plural': 'Admin - Category(Scope of Work)',
            },
        ),
        migrations.CreateModel(
            name='SitePhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construction.Project')),
            ],
            options={
                'verbose_name': 'Project - SitePhotos',
                'verbose_name_plural': 'Project - SitePhotos',
            },
        ),
        migrations.CreateModel(
            name='SitePhotosDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=construction.models.project_sitephotos_path, verbose_name='Photos')),
                ('reveal', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Let the client view this?')),
                ('sitephotos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construction.SitePhotos')),
            ],
            options={
                'verbose_name': 'Site Photos',
                'verbose_name_plural': 'Site Photos',
            },
        ),
        migrations.CreateModel(
            name='ScopeOfWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=255, null=True, verbose_name='Description')),
                ('materialcost', models.FloatField(default=0, verbose_name='Material Cost')),
                ('laborcost', models.FloatField(default=0, verbose_name='Labor Cost')),
                ('subbid', models.FloatField(default=0, verbose_name='Sub bid')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.ScopeOfWorkCategory')),
            ],
            options={
                'verbose_name': 'Admin - Scope Of Work',
                'verbose_name_plural': 'Admin - Scope Of Work',
            },
        ),
        migrations.CreateModel(
            name='ReworkBeforeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=construction.models.rework_upload_path)),
                ('rework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.Rework')),
            ],
        ),
        migrations.CreateModel(
            name='ReworkAfterImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=construction.models.rework_upload_path)),
                ('rework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.Rework')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=construction.models.requisition_upload_path, verbose_name='Image')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.Requisition')),
            ],
            options={
                'verbose_name': 'Requisition Image(dr/image proof)',
                'verbose_name_plural': 'Requisition Image(dr/image proof)',
            },
        ),
        migrations.CreateModel(
            name='RequisitionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles', models.CharField(max_length=255, verbose_name='Articles')),
                ('quantity', models.IntegerField(default=1, verbose_name='Request Quantity')),
                ('unit', models.CharField(blank=True, max_length=255, null=True, verbose_name='Unit')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitiondetail', to='construction.Requisition', verbose_name='Requesition')),
            ],
            options={
                'verbose_name': 'Requisition Detail',
                'verbose_name_plural': 'Requisition Details',
            },
        ),
        migrations.CreateModel(
            name='RequisitionDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles', models.CharField(max_length=255, verbose_name='Articles')),
                ('quantity', models.IntegerField(default=0, null=True, verbose_name='Delivered Quantity')),
                ('unit', models.CharField(blank=True, max_length=255, null=True, verbose_name='Unit')),
                ('unit_price', models.FloatField(blank=True, null=True, verbose_name='Unit Price')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Canceled', 'Canceled'), ('To be delivered', 'To be delivered')], max_length=255, null=True, verbose_name='Status')),
                ('status2', models.CharField(blank=True, choices=[('Not Received', 'Not Received'), ('Incomplete', 'Incomplete'), ('Complete', 'Complete')], max_length=255, null=True, verbose_name='Action')),
                ('quantity2', models.IntegerField(blank=True, default=0, null=True, verbose_name='Received Quantity')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.Requisition', verbose_name='Requesition')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_of_work', models.CharField(max_length=255, verbose_name='Scope Of Work')),
                ('unit', models.CharField(blank=True, max_length=255)),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('unit_cost', models.FloatField(default=0, verbose_name='Unit Cost')),
                ('amount', models.FloatField(default=0, verbose_name='Amount')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.Quotation')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectProgressDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_of_work', models.CharField(max_length=255, verbose_name='Scope of Work')),
                ('level', models.IntegerField(choices=[(5, 'high'), (1, 'low'), (3, 'medium')], default=1, verbose_name='Level')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('On-going', 'On-going')], default='Pending', max_length=255, verbose_name='Status')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Completion Date')),
                ('projectprogress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.ProjectProgress')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectIssues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectissue', to='construction.Project')),
                ('whm', models.ForeignKey(help_text='Warehouseman', limit_choices_to={'groups__name': 'Warehouseman'}, on_delete=django.db.models.deletion.CASCADE, related_name='projectissue_whm', to=settings.AUTH_USER_MODEL, verbose_name='Prepared by:')),
            ],
            options={
                'verbose_name': 'Project - Project Issues',
                'verbose_name_plural': 'Project - Project Issues',
            },
        ),
        migrations.CreateModel(
            name='ProjectInventoryDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles', models.CharField(max_length=255, verbose_name='Articles')),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.ProjectInventory', verbose_name='Project Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBlueprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=construction.models.project_upload_path, verbose_name='Blueprint/ Design/ Reference')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.Province', verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='project',
            name='typeofproject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.ProjectType', verbose_name='Project Type'),
        ),
        migrations.AddField(
            model_name='project',
            name='whm',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Warehouseman'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_whm', to=settings.AUTH_USER_MODEL, verbose_name='Warehouseman'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='user.png', upload_to=construction.models.profile_upload_path)),
                ('birthdate', models.DateField(help_text='Format: yyyy-mm-dd', null=True, verbose_name='Birth date')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=15, verbose_name='Phone')),
                ('address', models.CharField(help_text='Apartment, suite, unit, building, floor, street, barangay', max_length=255)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.City', verbose_name='City')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.Gender')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.Province', verbose_name='Province')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='PersonnelJobOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joborder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.JobOrderTask')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.Personnel')),
            ],
        ),
        migrations.AddField(
            model_name='personnel',
            name='personnel_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.PersonnelType'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.Province', verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='skill',
            field=models.ManyToManyField(related_name='personnel', to='construction.PersonnelSkill'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialReportDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('articles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.ProjectInventoryDetails')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construction.MaterialReport')),
            ],
        ),
        migrations.AddField(
            model_name='materialreport',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construction.Project'),
        ),
        migrations.AddField(
            model_name='materialreport',
            name='whm',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Warehouseman'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dailyreport_whm', to=settings.AUTH_USER_MODEL, verbose_name='Warehouseman'),
        ),
        migrations.CreateModel(
            name='LandingPageTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Title')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.LandingPageCategory')),
            ],
        ),
        migrations.CreateModel(
            name='LandingPageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=construction.models.landingpage_image_path, verbose_name='Image')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.LandingPageTitle')),
            ],
        ),
        migrations.AddField(
            model_name='jobordertask',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobordertask', to='construction.Personnel', verbose_name='Personnel'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joborder', to='construction.Project', verbose_name='Project'),
        ),
        migrations.CreateModel(
            name='ExternalProjectInventoryDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.ExternalProjectInventory', verbose_name='Project Inventory')),
            ],
        ),
        migrations.AddField(
            model_name='externalprojectinventory',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='construction.Project', verbose_name='Project'),
        ),
        migrations.CreateModel(
            name='ExternalOrderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=construction.models.externalorder_upload_path, verbose_name='OR/Reciept/Materials')),
                ('externalorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.ExternalOrder')),
            ],
            options={
                'verbose_name': 'External Order Image',
            },
        ),
        migrations.CreateModel(
            name='ExternalOrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name=())),
                ('unit', models.CharField(max_length=255, verbose_name='Unit')),
                ('articles', models.CharField(max_length=255, verbose_name='Article')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='Remarks')),
                ('unitprice', models.FloatField(verbose_name='Unit Price')),
                ('externalorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='externalorderdetails', to='construction.ExternalOrder', verbose_name='Outside Purchase')),
            ],
            options={
                'verbose_name': 'External Order Detail',
                'verbose_name_plural': 'External Order Details',
            },
        ),
        migrations.AddField(
            model_name='externalorder',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='externalorder_project', to='construction.Project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='externalorder',
            name='whm',
            field=models.ForeignKey(help_text='Warehouseman', limit_choices_to={'groups__name': 'Warehouseman'}, on_delete=django.db.models.deletion.CASCADE, related_name='externalorder_whm', to=settings.AUTH_USER_MODEL, verbose_name='Prepared By'),
        ),
        migrations.CreateModel(
            name='ExternalMaterialReportDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('articles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.ExternalProjectInventoryDetails')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construction.ExternalMaterialReport')),
            ],
        ),
        migrations.AddField(
            model_name='externalmaterialreport',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construction.Project'),
        ),
        migrations.AddField(
            model_name='externalmaterialreport',
            name='whm',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Warehouseman'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Warehouseman'),
        ),
        migrations.CreateModel(
            name='EstimateImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=construction.models.estimate_upload_path, verbose_name='Image/Design/Reference')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.Estimate')),
            ],
        ),
        migrations.AddField(
            model_name='estimate',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.Province', verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='typeofproject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.ProjectType', verbose_name='Project Type'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.Province'),
        ),
    ]
