# Generated by Django 3.0.4 on 2020-05-28 13:17

import construction.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=255, null=True, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=255, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=255, null=True, verbose_name='Last Name')),
                ('suffix', models.CharField(blank=True, max_length=255, verbose_name='Suffix')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='ExternalOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('amount', models.FloatField(default=0, verbose_name='Amount')),
            ],
            options={
                'verbose_name': 'Outside Purchase',
                'verbose_name_plural': 'Outside Purchases',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternate_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alternate Code')),
                ('item_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Item Code')),
                ('unit', models.CharField(blank=True, max_length=255, null=True, verbose_name='Unit')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('quantity', models.FloatField(default=0, verbose_name='Quantity')),
                ('unit_price', models.FloatField(blank=True, null=True, verbose_name='Unit Price')),
            ],
            options={
                'verbose_name_plural': 'Inventory Office',
            },
        ),
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date Given')),
                ('duration', models.DateField(verbose_name='Duration')),
                ('pic', models.ForeignKey(limit_choices_to={'groups__name': 'Person In-Charge'}, on_delete=django.db.models.deletion.CASCADE, related_name='joborder_pic', to=settings.AUTH_USER_MODEL, verbose_name='Prepared by')),
            ],
            options={
                'verbose_name': 'Job Order',
                'verbose_name_plural': 'Job Orders',
            },
        ),
        migrations.CreateModel(
            name='PersonnelSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255, verbose_name='Skill')),
            ],
            options={
                'verbose_name': 'Personnel Skills',
                'verbose_name_plural': 'Personnel Skills',
            },
        ),
        migrations.CreateModel(
            name='ProjectIssues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.TextField()),
                ('pic', models.ForeignKey(help_text='Person In-Charge', limit_choices_to={'groups__name': 'Person In-Charge'}, on_delete=django.db.models.deletion.CASCADE, related_name='projectissue_pic', to=settings.AUTH_USER_MODEL, verbose_name='Send to: ')),
            ],
            options={
                'verbose_name': 'Project Issue',
                'verbose_name_plural': 'Project Issues',
            },
        ),
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_progress', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectsite', models.CharField(max_length=255, null=True, verbose_name='Project Site')),
                ('address', models.CharField(help_text='Apartment, suite, unit, building, floor, street, barangay', max_length=255, null=True, verbose_name='Address')),
                ('status', models.CharField(blank=True, choices=[('On-going', 'On-going'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=255)),
                ('typeofproject', models.CharField(choices=[('Concrete Countertops', 'Concrete Countertops'), ('Self-Leveling Floor Applcation', 'Self-Leveling Floor Applcation'), ('Industrial Cement Flooring Finish', 'Industrial Cement Flooring Finish'), ('Interior Fit-out Works', 'Interior Fit-outWorks'), ('General Construction', 'General Construction')], max_length=255, null=True, verbose_name='Project Type')),
                ('lotarea', models.CharField(blank=True, max_length=255, verbose_name='Lot Area')),
                ('startdate', models.DateField(blank=True, help_text='Format: YYYY-MM-DD', verbose_name='Start Project Date')),
                ('comdate', models.DateField(blank=True, help_text='Format: YYYY-MM-DD', verbose_name='Project Completion Date')),
                ('mpd', models.DateField(blank=True, help_text='Format: YYYY-MM-DD', verbose_name='Maintenance Period End Date')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.City', verbose_name='City/Municipality')),
                ('client', models.ForeignKey(limit_choices_to={'groups__name': 'Client'}, on_delete=django.db.models.deletion.CASCADE, related_name='projectsite_client', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('pic', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Person In-Charge'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectsite_pic', to=settings.AUTH_USER_MODEL, verbose_name='Person In Charge')),
                ('pm', models.ForeignKey(limit_choices_to={'groups__name': 'Project Manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='projectsite_pm', to=settings.AUTH_USER_MODEL, verbose_name='Project Manager')),
            ],
            options={
                'verbose_name': 'Projects',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subject')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('amount', models.FloatField(default=0, verbose_name='Total Amount')),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=255, verbose_name='Status')),
                ('projectsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='construction.ProjectSite', verbose_name='Project Site')),
            ],
            options={
                'verbose_name': 'Quotation',
                'verbose_name_plural': 'Quotations',
            },
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('admin', models.ForeignKey(help_text='Admin', limit_choices_to={'groups__name': 'Admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='requisition_admin', to=settings.AUTH_USER_MODEL, verbose_name='Send To?')),
                ('projectsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_project', to='construction.ProjectSite', verbose_name='Project Site')),
                ('whm', models.ForeignKey(help_text='Warehouseman', limit_choices_to={'groups__name': 'Warehouseman'}, on_delete=django.db.models.deletion.CASCADE, related_name='requisition_whm', to=settings.AUTH_USER_MODEL, verbose_name='Prepared by')),
            ],
            options={
                'verbose_name': 'Requisition Form',
                'verbose_name_plural': 'Requisition Form',
            },
        ),
        migrations.CreateModel(
            name='ScopeOfWorkCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Scope Of Work',
                'verbose_name_plural': 'Scope Of Work Categories',
            },
        ),
        migrations.CreateModel(
            name='WeeklyStatusReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dategiven', models.DateField(verbose_name='Date Given')),
                ('duration', models.DateField(verbose_name='Duration')),
                ('pic', models.ForeignKey(limit_choices_to={'groups__name': 'Project In-Charge'}, on_delete=django.db.models.deletion.CASCADE, related_name='wsr_pic', to=settings.AUTH_USER_MODEL, verbose_name='Project In-Charge')),
                ('projectsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.ProjectSite')),
            ],
            options={
                'verbose_name': 'Weekly Status Report',
                'verbose_name_plural': 'Weekly Status Report',
            },
        ),
        migrations.CreateModel(
            name='SitePhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.FileField(upload_to=construction.models.project_upload_path, verbose_name='Photos')),
                ('date', models.DateField(default=datetime.date.today)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitephotos', to='construction.WeeklyStatusReport')),
            ],
            options={
                'verbose_name': 'Site Photos',
                'verbose_name_plural': 'Site Photos',
            },
        ),
        migrations.CreateModel(
            name='ScopeOfWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=255, null=True, verbose_name='Description')),
                ('materialcost', models.FloatField(blank=True, verbose_name='Material Cost')),
                ('laborcost', models.FloatField(blank=True, verbose_name='Labor Cost')),
                ('subbid', models.FloatField(blank=True, verbose_name='Sub bid')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.ScopeOfWorkCategory')),
            ],
            options={
                'verbose_name': 'Scope Of Work',
                'verbose_name_plural': 'Scope Of Works',
            },
        ),
        migrations.CreateModel(
            name='Rework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('instruction', models.TextField()),
                ('pic', models.ForeignKey(limit_choices_to={'groups__name': 'Person In-Charge'}, on_delete=django.db.models.deletion.CASCADE, related_name='rework_pic', to=settings.AUTH_USER_MODEL, verbose_name='Person In-Charge')),
                ('pm', models.ForeignKey(limit_choices_to={'groups__name': 'Project Manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='rework_pm', to=settings.AUTH_USER_MODEL, verbose_name='Project Manager')),
                ('projectsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reworkform', to='construction.ProjectSite', verbose_name='Project Site')),
            ],
            options={
                'verbose_name': 'Rework Form',
                'verbose_name_plural': 'Rework Form',
            },
        ),
        migrations.CreateModel(
            name='RequisitionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Purchased', 'Purchased'), ('Delivered', 'Delivered')], default='Pending', max_length=255, verbose_name='Status')),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.Inventory', verbose_name='Articles')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitiondetail', to='construction.Requisition', verbose_name='Requesition')),
            ],
            options={
                'verbose_name': 'Requisition Form Detail',
                'verbose_name_plural': 'Requisition Form Details',
            },
        ),
        migrations.CreateModel(
            name='RequestForTheWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('quantity', models.IntegerField(blank=True, verbose_name='Quantity')),
                ('unit', models.CharField(blank=True, max_length=255, verbose_name='Unit')),
                ('request', models.CharField(max_length=255, verbose_name='Request')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestfortheweek', to='construction.WeeklyStatusReport')),
            ],
            options={
                'verbose_name': 'Request for the Next Week',
                'verbose_name_plural': 'Request for the Next Week',
            },
        ),
        migrations.CreateModel(
            name='QuotationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, max_length=255)),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.Quotation')),
                ('scope_of_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotationsow', to='construction.ScopeOfWork', verbose_name='quotation')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=255)),
                ('target', models.CharField(blank=True, max_length=255)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectstatus', to='construction.WeeklyStatusReport')),
            ],
            options={
                'verbose_name': 'Project Status',
                'verbose_name_plural': 'Project Status',
            },
        ),
        migrations.CreateModel(
            name='ProjectSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.TextField(verbose_name='Possible Solution')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem', to='construction.ProjectIssues', verbose_name='projectissue')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.WeeklyStatusReport')),
            ],
            options={
                'verbose_name': 'Issues',
                'verbose_name_plural': 'Issues',
            },
        ),
        migrations.AddField(
            model_name='projectsite',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.Province', verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='projectsite',
            name='whm',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Warehouseman'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectsite_whm', to=settings.AUTH_USER_MODEL, verbose_name='Warehouseman'),
        ),
        migrations.CreateModel(
            name='ProjectProgressDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_of_work', models.CharField(max_length=255, verbose_name='Scope of Work')),
                ('level', models.IntegerField(choices=[(1, 'low'), (3, 'medium'), (5, 'high')], default=1, verbose_name='Level')),
                ('status', models.CharField(choices=[('Done', 'Done'), ('On-going', 'On-going'), ('Pending', 'Pending')], default='Pending', max_length=255, verbose_name='Status')),
                ('projectprogress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.ProjectProgress')),
            ],
        ),
        migrations.AddField(
            model_name='projectprogress',
            name='projectsite',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='construction.ProjectSite'),
        ),
        migrations.AddField(
            model_name='projectissues',
            name='projectsite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectissue', to='construction.ProjectSite'),
        ),
        migrations.AddField(
            model_name='projectissues',
            name='whm',
            field=models.ForeignKey(help_text='Warehouseman', limit_choices_to={'groups__name': 'Warehouseman'}, on_delete=django.db.models.deletion.CASCADE, related_name='projectissue_whm', to=settings.AUTH_USER_MODEL, verbose_name='Prepared by:'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='user.png', upload_to=construction.models.profile_upload_path)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, verbose_name='Sex')),
                ('birthdate', models.DateField(help_text='Format: yyyy-mm-dd', null=True, verbose_name='Birth date')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=15, verbose_name='Phone')),
                ('address', models.CharField(blank=True, help_text='Apartment, suite, unit, building, floor, street, barangay', max_length=255)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.City', verbose_name='City/Municipality')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.Province', verbose_name='Province')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=255, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Nane')),
                ('suffix', models.CharField(blank=True, max_length=50, verbose_name='Suffix')),
                ('contact', models.CharField(max_length=20, verbose_name='Contach Number')),
                ('personnel_type', models.CharField(choices=[('Subcontractor', 'Subcontractor'), ('Company Worker', 'Company Worker')], max_length=255, verbose_name='Type of Personnel')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='construction.PersonnelSkill')),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnel',
            },
        ),
        migrations.CreateModel(
            name='Manpower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('manpower', models.CharField(max_length=255, verbose_name='Man Power')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manpower', to='construction.WeeklyStatusReport')),
            ],
            options={
                'verbose_name': 'Man Power',
                'verbose_name_plural': 'Man Power',
            },
        ),
        migrations.CreateModel(
            name='JobOrderTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255, verbose_name='Activity of the Week')),
                ('duration', models.CharField(blank=True, max_length=255, null=True, verbose_name='Duration')),
                ('joborder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobordertask', to='construction.JobOrder', verbose_name='Joborder')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobordertask', to='construction.Personnel', verbose_name='Personnel')),
            ],
            options={
                'verbose_name': 'Job Order Task',
                'verbose_name_plural': 'Job Order Tasks',
            },
        ),
        migrations.AddField(
            model_name='joborder',
            name='projectsite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joborder', to='construction.ProjectSite', verbose_name='Project Site'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='whm',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Warehouseman'}, on_delete=django.db.models.deletion.CASCADE, related_name='joborder_whm', to=settings.AUTH_USER_MODEL, verbose_name='Send to'),
        ),
        migrations.CreateModel(
            name='ExternalOrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name=())),
                ('unit', models.CharField(max_length=255, verbose_name='Unit')),
                ('articles', models.CharField(max_length=255, verbose_name='Article')),
                ('unitprice', models.FloatField(verbose_name='Unit Price')),
                ('externalorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='externalorderdetails', to='construction.ExternalOrder', verbose_name='Outside Purchase')),
            ],
            options={
                'verbose_name': 'External Order Detail',
                'verbose_name_plural': 'External Order Details',
            },
        ),
        migrations.AddField(
            model_name='externalorder',
            name='projectsite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='externalorder_project', to='construction.ProjectSite', verbose_name='Project Site'),
        ),
        migrations.AddField(
            model_name='externalorder',
            name='whm',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Warehouseman'}, on_delete=django.db.models.deletion.CASCADE, related_name='externalorder_whm', to=settings.AUTH_USER_MODEL, verbose_name='Prepared By'),
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=construction.models.project_upload_path, verbose_name='Photos')),
                ('date', models.DateField(default=datetime.date.today)),
                ('projectsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.ProjectSite')),
            ],
            options={
                'verbose_name': 'Site Photos',
                'verbose_name_plural': 'Site Photos',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.Province'),
        ),
    ]
