# Generated by Django 3.0.7 on 2020-07-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0002_auto_20200701_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectprogressdetails',
            name='level',
            field=models.IntegerField(choices=[(3, 'medium'), (5, 'high'), (1, 'low')], default=1, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed (Overdue)', 'Completed (Overdue)'), ('Completed', 'Completed'), ('On-going', 'On-going')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='requisitiondelivery',
            name='quantity',
            field=models.IntegerField(default=0, null=True, verbose_name='Delivered Quantity'),
        ),
        migrations.AlterField(
            model_name='requisitiondelivery',
            name='quantity2',
            field=models.IntegerField(default=0, null=True, verbose_name='Received Quantity'),
        ),
    ]
