# Generated by Django 3.0.4 on 2020-06-04 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0004_auto_20200601_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Currently Assigned', 'Currently Assigned')], default=1, max_length=255, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='externalorder',
            name='whm',
            field=models.ForeignKey(help_text='Warehouseman', limit_choices_to={'groups__name': 'Warehouseman'}, on_delete=django.db.models.deletion.CASCADE, related_name='externalorder_whm', to=settings.AUTH_USER_MODEL, verbose_name='Prepared By'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='contact',
            field=models.CharField(max_length=20, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='personnel_type',
            field=models.CharField(choices=[('Company Worker', 'Company Worker'), ('Subcontractor', 'Subcontractor')], max_length=255, verbose_name='Type of Personnel'),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='typeofproject',
            field=models.CharField(choices=[('Interior Fit-out Works', 'Interior Fit-outWorks'), ('Self-Leveling Floor Applcation', 'Self-Leveling Floor Applcation'), ('Industrial Cement Flooring Finish', 'Industrial Cement Flooring Finish'), ('General Construction', 'General Construction'), ('Concrete Countertops', 'Concrete Countertops')], max_length=255, null=True, verbose_name='Project Type'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Pending', 'Pending')], default='Pending', max_length=255, verbose_name='Status'),
        ),
    ]
