# Generated by Django 3.0.7 on 2020-07-08 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0006_auto_20200708_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Currently Assigned', 'Currently Assigned')], default='Available', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('On-going', 'On-going'), ('Completed (Overdue)', 'Completed (Overdue)'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectprogressdetails',
            name='level',
            field=models.IntegerField(choices=[(3, 'medium'), (5, 'high'), (1, 'low')], default=1, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='requisitiondelivery',
            name='status2',
            field=models.CharField(blank=True, choices=[('Incomplete', 'Incomplete'), ('Complete', 'Complete'), ('Not Received', 'Not Received')], max_length=255, null=True, verbose_name='Action'),
        ),
    ]
