# Generated by Django 3.0.8 on 2020-07-20 12:18

import construction.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0009_auto_20200714_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Landing Page Image Category')),
            ],
            options={
                'verbose_name': 'Admin - Landing Page Image Categories',
                'verbose_name_plural': 'Admin - Landing Page Image Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='projectinventory',
            options={'verbose_name': 'Project - Material Inventory(onsite)', 'verbose_name_plural': 'Project - Material Inventory(onsite)'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='design',
        ),
        migrations.AddField(
            model_name='quotation',
            name='is_vat',
            field=models.BooleanField(default=False, verbose_name='is VAT included?'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='jobordertask',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('On-going', 'On-going'), ('Pending', 'Pending')], default='Pending', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='status',
            field=models.CharField(choices=[('Currently Assigned', 'Currently Assigned'), ('Available', 'Available')], default='Available', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('Completed (Overdue)', 'Completed (Overdue)'), ('Completed', 'Completed'), ('On-going', 'On-going'), ('Pending', 'Pending')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectprogressdetails',
            name='level',
            field=models.IntegerField(choices=[(5, 'high'), (3, 'medium'), (1, 'low')], default=1, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='projectprogressdetails',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('On-going', 'On-going'), ('Pending', 'Pending')], default='Pending', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Accepted', 'Accepted')], default='Pending', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requisition_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='requisition number'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('Closed', 'Closed'), ('Pending', 'Pending'), ('To be Delivered', 'To be Delivered')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='requisitiondelivery',
            name='status2',
            field=models.CharField(blank=True, choices=[('Complete', 'Complete'), ('Incomplete', 'Incomplete'), ('Not Received', 'Not Received')], max_length=255, null=True, verbose_name='Action'),
        ),
        migrations.CreateModel(
            name='ProjectBlueprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=construction.models.project_upload_path, verbose_name='Blueprint/ Design/ Reference')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.Project')),
            ],
        ),
        migrations.CreateModel(
            name='LandingPageTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Title')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.LandingPageCategory')),
            ],
        ),
        migrations.CreateModel(
            name='LandingPageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=construction.models.landingpage_image_path, verbose_name='Image')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.LandingPageTitle')),
            ],
        ),
    ]
