# Generated by Django 3.0.4 on 2020-06-07 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0013_auto_20200605_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='admin',
        ),
        migrations.AddField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('Complied', 'Complied'), ('Pending', 'Pending')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='projectsite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='construction.ProjectSite'),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='date',
            field=models.DateField(help_text='Format: yyyy-mm-dd', verbose_name='Date Given'),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='duration',
            field=models.DateField(help_text='Format: yyyy-mm-dd', verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='jobordertask',
            name='status',
            field=models.CharField(choices=[('On-going', 'On-going'), ('Done', 'Done'), ('Pending', 'Pending')], default='Pending', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='projectprogressdetails',
            name='level',
            field=models.IntegerField(choices=[(3, 'medium'), (5, 'high'), (1, 'low')], default=1, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='typeofproject',
            field=models.CharField(choices=[('Interior Fit-out Works', 'Interior Fit-outWorks'), ('Industrial Cement Flooring Finish', 'Industrial Cement Flooring Finish'), ('Concrete Countertops', 'Concrete Countertops'), ('Self-Leveling Floor Applcation', 'Self-Leveling Floor Applcation'), ('General Construction', 'General Construction')], max_length=255, null=True, verbose_name='Project Type'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Pending', 'Pending')], default='Pending', max_length=255, verbose_name='Status'),
        ),
    ]
