# Generated by Django 3.0.7 on 2020-07-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0017_auto_20200704_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='lotarea',
            field=models.CharField(blank=True, help_text='Please indicate if square meter, hectare, acre', max_length=255, verbose_name='Lot Area'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='message',
            field=models.TextField(null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='jobordertask',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('On-going', 'On-going'), ('Pending', 'Pending')], default='Pending', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='projectprogressdetails',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('On-going', 'On-going'), ('Pending', 'Pending')], default='Pending', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='lotarea',
            field=models.CharField(blank=True, help_text='Please indicate if square meter, hectare, acre', max_length=255, verbose_name='Lot Area'),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='status',
            field=models.CharField(blank=True, choices=[('Completed (Overdue)', 'Completed (Overdue)'), ('Completed', 'Completed'), ('On-going', 'On-going'), ('Pending', 'Pending')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('To be Delivered', 'To be Delivered'), ('Closed', 'Closed'), ('Pending', 'Pending')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='requisitiondelivery',
            name='status2',
            field=models.CharField(blank=True, choices=[('Complete', 'Complete'), ('Not Received', 'Not Received'), ('Incomplete', 'Incomplete')], max_length=255, null=True, verbose_name='Action'),
        ),
    ]
