# Generated by Django 3.0.8 on 2020-07-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0026_auto_20200723_1345'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExternalOrderReport',
            new_name='ExternalMaterialReport',
        ),
        migrations.RenameModel(
            old_name='ExternalOrderDetailsReport',
            new_name='ExternalMaterialReportDetails',
        ),
        migrations.RenameModel(
            old_name='ProjectDailyReport',
            new_name='MaterialReport',
        ),
        migrations.RenameModel(
            old_name='ProjectDailyReportDetails',
            new_name='MaterialReportDetails',
        ),
        migrations.AlterField(
            model_name='jobordertask',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('On-going', 'On-going')], default='Pending', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed (Overdue)', 'Completed (Overdue)'), ('On-going', 'On-going'), ('Completed', 'Completed')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectprogressdetails',
            name='level',
            field=models.IntegerField(choices=[(1, 'low'), (3, 'medium'), (5, 'high')], default=1, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='projectprogressdetails',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('On-going', 'On-going')], default='Pending', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='requisitiondelivery',
            name='status2',
            field=models.CharField(blank=True, choices=[('Incomplete', 'Incomplete'), ('Complete', 'Complete'), ('Not Received', 'Not Received')], max_length=255, null=True, verbose_name='Action'),
        ),
    ]
