# Generated by Django 3.0.4 on 2020-06-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0026_auto_20200609_2257'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyReport',
            new_name='DailySitePhotos',
        ),
        migrations.RemoveField(
            model_name='projectsolution',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='projectsolution',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='projectstatus',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='sitephotos',
            name='reference',
        ),
        migrations.AlterField(
            model_name='jobordertask',
            name='status',
            field=models.CharField(choices=[('On-going', 'On-going'), ('Pending', 'Pending'), ('Done', 'Done')], default='Pending', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='personnel_type',
            field=models.CharField(choices=[('Company Worker', 'Company Worker'), ('Subcontractor', 'Subcontractor')], max_length=255, verbose_name='Type of Personnel'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Currently Assigned', 'Currently Assigned')], default='Available', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='projectprogressdetails',
            name='level',
            field=models.IntegerField(choices=[(5, 'high'), (3, 'medium'), (1, 'low')], default=1, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='projectprogressdetails',
            name='status',
            field=models.CharField(choices=[('On-going', 'On-going'), ('Pending', 'Pending'), ('Done', 'Done')], default='Pending', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='status',
            field=models.CharField(blank=True, choices=[('On-going', 'On-going'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='typeofproject',
            field=models.CharField(choices=[('General Construction', 'General Construction'), ('Interior Fit-out Works', 'Interior Fit-outWorks'), ('Industrial Cement Flooring Finish', 'Industrial Cement Flooring Finish'), ('Self-Leveling Floor Applcation', 'Self-Leveling Floor Applcation'), ('Concrete Countertops', 'Concrete Countertops')], max_length=255, null=True, verbose_name='Project Type'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('Closed', 'Closed'), ('Pending', 'Pending'), ('To be Delivered', 'To be Delivered')], default='Pending', max_length=255),
        ),
        migrations.DeleteModel(
            name='Manpower',
        ),
        migrations.DeleteModel(
            name='ProjectSolution',
        ),
        migrations.DeleteModel(
            name='ProjectStatus',
        ),
        migrations.DeleteModel(
            name='SitePhotos',
        ),
    ]
