# Generated by Django 3.0.7 on 2020-06-10 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0027_auto_20200610_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='jobordertask',
            name='status',
            field=models.CharField(choices=[('On-going', 'On-going'), ('Done', 'Done'), ('Pending', 'Pending')], default='Pending', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='personnel_type',
            field=models.CharField(choices=[('Subcontractor', 'Subcontractor'), ('Company Worker', 'Company Worker')], max_length=255, verbose_name='Type of Personnel'),
        ),
        migrations.AlterField(
            model_name='projectprogressdetails',
            name='level',
            field=models.IntegerField(choices=[(1, 'low'), (3, 'medium'), (5, 'high')], default=1, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='projectprogressdetails',
            name='status',
            field=models.CharField(choices=[('On-going', 'On-going'), ('Done', 'Done'), ('Pending', 'Pending')], default='Pending', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='status',
            field=models.CharField(blank=True, choices=[('On-going', 'On-going'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='typeofproject',
            field=models.CharField(choices=[('General Construction', 'General Construction'), ('Concrete Countertops', 'Concrete Countertops'), ('Interior Fit-out Works', 'Interior Fit-outWorks'), ('Industrial Cement Flooring Finish', 'Industrial Cement Flooring Finish'), ('Self-Leveling Floor Applcation', 'Self-Leveling Floor Applcation')], max_length=255, null=True, verbose_name='Project Type'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('To be Delivered', 'To be Delivered'), ('Pending', 'Pending'), ('Closed', 'Closed')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='requisitiondetails',
            name='status2',
            field=models.CharField(blank=True, choices=[('Not Recieved', 'Not Recieved'), ('Complete', 'Complete'), ('Incomplete', 'Incomplete')], max_length=255, null=True, verbose_name='Action'),
        ),
        migrations.CreateModel(
            name='ProjectDailyReportDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('remarks', models.CharField(max_length=255, null=True)),
                ('articles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.Inventory')),
                ('dailyreport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construction.ProjectDailyReport')),
            ],
        ),
        migrations.AddField(
            model_name='projectdailyreport',
            name='projectsite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construction.ProjectSite'),
        ),
        migrations.AddField(
            model_name='projectdailyreport',
            name='whm',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Warehouseman'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dailyreport_whm', to=settings.AUTH_USER_MODEL, verbose_name='Warehouseman'),
        ),
    ]
