# Generated by Django 3.0.8 on 2020-07-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0027_auto_20200724_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='amount',
            new_name='total',
        ),
        migrations.AddField(
            model_name='quotationdetails',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='quotationdetails',
            name='unit_cost',
            field=models.FloatField(default=0, verbose_name='Unit Cost'),
        ),
        migrations.AlterField(
            model_name='jobordertask',
            name='status',
            field=models.CharField(choices=[('On-going', 'On-going'), ('Done', 'Done'), ('Pending', 'Pending')], default='Pending', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('On-going', 'On-going'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Completed (Overdue)', 'Completed (Overdue)')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectprogressdetails',
            name='level',
            field=models.IntegerField(choices=[(5, 'high'), (1, 'low'), (3, 'medium')], default=1, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='projectprogressdetails',
            name='status',
            field=models.CharField(choices=[('On-going', 'On-going'), ('Done', 'Done'), ('Pending', 'Pending')], default='Pending', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('Closed', 'Closed'), ('Pending', 'Pending'), ('To be Delivered', 'To be Delivered')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='requisitiondelivery',
            name='status2',
            field=models.CharField(blank=True, choices=[('Incomplete', 'Incomplete'), ('Not Received', 'Not Received'), ('Complete', 'Complete')], max_length=255, null=True, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='scopeofwork',
            name='laborcost',
            field=models.FloatField(default=0, verbose_name='Labor Cost'),
        ),
        migrations.AlterField(
            model_name='scopeofwork',
            name='materialcost',
            field=models.FloatField(default=0, verbose_name='Material Cost'),
        ),
        migrations.AlterField(
            model_name='scopeofwork',
            name='subbid',
            field=models.FloatField(default=0, verbose_name='Sub bid'),
        ),
    ]
