# Generated by Django 3.0.8 on 2020-07-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0029_auto_20200724_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('On-going', 'On-going'), ('Completed (Overdue)', 'Completed (Overdue)')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Accepted', 'Accepted')], default='Pending', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='quotationdetails',
            name='scope_of_work',
            field=models.CharField(max_length=255, verbose_name='Scope Of Work'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('Closed', 'Closed'), ('To be Delivered', 'To be Delivered'), ('Pending', 'Pending')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='requisitiondelivery',
            name='status2',
            field=models.CharField(blank=True, choices=[('Complete', 'Complete'), ('Incomplete', 'Incomplete'), ('Not Received', 'Not Received')], max_length=255, null=True, verbose_name='Action'),
        ),
    ]
