# Generated by Django 3.0.7 on 2020-06-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0033_auto_20200610_2153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailySitePhotos',
            new_name='SitePhotos',
        ),
        migrations.RenameModel(
            old_name='DailySitePhotosDetails',
            new_name='SitePhotosDetails',
        ),
        migrations.AlterField(
            model_name='jobordertask',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('On-going', 'On-going'), ('Pending', 'Pending')], default='Pending', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='personnel_type',
            field=models.CharField(choices=[('Subcontractor', 'Subcontractor'), ('Company Worker', 'Company Worker')], max_length=255, verbose_name='Type of Personnel'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='projectprogressdetails',
            name='level',
            field=models.IntegerField(choices=[(5, 'high'), (1, 'low'), (3, 'medium')], default=1, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='projectprogressdetails',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('On-going', 'On-going'), ('Pending', 'Pending')], default='Pending', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('On-going', 'On-going'), ('Pending', 'Pending')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='typeofproject',
            field=models.CharField(choices=[('Industrial Cement Flooring Finish', 'Industrial Cement Flooring Finish'), ('Self-Leveling Floor Applcation', 'Self-Leveling Floor Applcation'), ('Interior Fit-out Works', 'Interior Fit-outWorks'), ('Concrete Countertops', 'Concrete Countertops'), ('General Construction', 'General Construction')], max_length=255, null=True, verbose_name='Project Type'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Pending', 'Pending')], default='Pending', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('To be Delivered', 'To be Delivered'), ('Closed', 'Closed'), ('Pending', 'Pending')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='requisitiondetails',
            name='status2',
            field=models.CharField(blank=True, choices=[('Incomplete', 'Incomplete'), ('Complete', 'Complete'), ('Not Recieved', 'Not Recieved')], max_length=255, null=True, verbose_name='Action'),
        ),
    ]
