# Generated by Django 3.0.7 on 2020-06-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0037_auto_20200622_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joborder',
            name='whm',
        ),
        migrations.AlterField(
            model_name='personnel',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Currently Assigned', 'Currently Assigned')], default='Available', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='projectprogressdetails',
            name='level',
            field=models.IntegerField(choices=[(1, 'low'), (3, 'medium'), (5, 'high')], default=1, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('On-going', 'On-going')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='typeofproject',
            field=models.CharField(choices=[('General Construction', 'General Construction'), ('Self-Leveling Floor Applcation', 'Self-Leveling Floor Applcation'), ('Concrete Countertops', 'Concrete Countertops'), ('Interior Fit-out Works', 'Interior Fit-outWorks'), ('Industrial Cement Flooring Finish', 'Industrial Cement Flooring Finish')], max_length=255, null=True, verbose_name='Project Type'),
        ),
        migrations.AlterField(
            model_name='requisitiondetails',
            name='status2',
            field=models.CharField(blank=True, choices=[('Not Recieved', 'Not Recieved'), ('Incomplete', 'Incomplete'), ('Complete', 'Complete')], max_length=255, null=True, verbose_name='Action'),
        ),
    ]
