# Generated by Django 3.0.7 on 2020-06-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0065_auto_20200630_0821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Admin - City'},
        ),
        migrations.AlterModelOptions(
            name='externalorder',
            options={'verbose_name': 'ProjectSite - External Order', 'verbose_name_plural': 'ProjectSite - External Order'},
        ),
        migrations.AlterModelOptions(
            name='externalprojectinventory',
            options={'verbose_name': 'ProjectSite - External Inventory', 'verbose_name_plural': 'ProjectSite - External Inventory'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Admin - Material Inventory Office'},
        ),
        migrations.AlterModelOptions(
            name='joborder',
            options={'verbose_name': 'ProjectSite - Job Order', 'verbose_name_plural': 'ProjectSite - Job Order'},
        ),
        migrations.AlterModelOptions(
            name='personnelskill',
            options={'verbose_name': 'Admin - Personnel Skills', 'verbose_name_plural': 'Admin - Personnel Skills'},
        ),
        migrations.AlterModelOptions(
            name='projectinventory',
            options={'verbose_name': 'ProjectSite - Inventory(onsite)', 'verbose_name_plural': 'ProjectSite - Inventory(onsite)'},
        ),
        migrations.AlterModelOptions(
            name='projectissues',
            options={'verbose_name': 'Admin - Project Issues', 'verbose_name_plural': 'Admin - Project Issues'},
        ),
        migrations.AlterModelOptions(
            name='projectsite',
            options={'verbose_name': 'ProjectSite', 'verbose_name_plural': 'ProjectSite'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'Admin - Province', 'verbose_name_plural': 'Admin - Province'},
        ),
        migrations.AlterModelOptions(
            name='quotation',
            options={'verbose_name': 'ProjectSite - Quotation', 'verbose_name_plural': 'ProjectSite - Quotation'},
        ),
        migrations.AlterModelOptions(
            name='requisition',
            options={'verbose_name': 'ProjectSite - Requisition', 'verbose_name_plural': 'ProjectSite - Requisition'},
        ),
        migrations.AlterModelOptions(
            name='requisitiondetails',
            options={'verbose_name': 'Requisition Detail', 'verbose_name_plural': 'Requisition Details'},
        ),
        migrations.AlterModelOptions(
            name='rework',
            options={'verbose_name': 'ProjectSite - Rework', 'verbose_name_plural': 'ProjectSite - Rework'},
        ),
        migrations.AlterModelOptions(
            name='scopeofwork',
            options={'verbose_name': 'Admin - Scope Of Work', 'verbose_name_plural': 'Admin - Scope Of Work'},
        ),
        migrations.AlterModelOptions(
            name='scopeofworkcategory',
            options={'verbose_name': 'Admin - Category(Scope of Work)', 'verbose_name_plural': 'Admin - Category(Scope of Work)'},
        ),
        migrations.AlterModelOptions(
            name='sitephotos',
            options={'verbose_name': 'ProjectSite - SitePhotos', 'verbose_name_plural': 'ProjectSite - SitePhotos'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Admin - User', 'verbose_name_plural': 'Admin - User'},
        ),
        migrations.AlterField(
            model_name='personnel',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='status',
            field=models.CharField(choices=[('Currently Assigned', 'Currently Assigned'), ('Available', 'Available')], default='Available', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='projectprogressdetails',
            name='level',
            field=models.IntegerField(choices=[(5, 'high'), (3, 'medium'), (1, 'low')], default=1, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed (Overdue)', 'Completed (Overdue)'), ('Completed', 'Completed'), ('On-going', 'On-going')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='typeofproject',
            field=models.CharField(choices=[('Self-Leveling Floor Applcation', 'Self-Leveling Floor Applcation'), ('Interior Fit-out Works', 'Interior Fit-outWorks'), ('Industrial Cement Flooring Finish', 'Industrial Cement Flooring Finish'), ('Concrete Countertops', 'Concrete Countertops'), ('General Construction', 'General Construction')], max_length=255, null=True, verbose_name='Project Type'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Closed', 'Closed'), ('To be Delivered', 'To be Delivered')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='requisitiondetails',
            name='status2',
            field=models.CharField(blank=True, choices=[('Not Received', 'Not Received'), ('Incomplete', 'Incomplete'), ('Complete', 'Complete')], max_length=255, null=True, verbose_name='Action'),
        ),
    ]
